export const EQUIPMENT = {
  HELM: "EQUIPMENT_HELM",
  CHEST: {
    BODY: {
      UNTUCKED: "EQUIPMENT_CHEST_BODY_UNTUCKED",
      TUCKED: "EQUIPMENT_CHEST_BODY_TUCKED"
    },
    OFFHAND: {
      ONE_HANDED: "EQUIPMENT_OFFHAND_ONE_HANDED",
      TWO_HANDED: "EQUIPMENT_OFFHAND_TWO_HANDED",
      CROSSBOW_ONE_HANDED: "EQUIPMENT_OFFHAND_CROSSBOW_ONE_HANDED",
      CROSSBOW_TWO_HANDED: "EQUIPMENT_OFFHAND_CROSSBOW_TWO_HANDED",
      THROWING: "EQUIPMENT_OFFHAND_THROWING"
    },
    MAINHAND: {
      ONE_HANDED: "EQUIPMENT_MAINHAND_ONE_HANDED",
      TWO_HANDED: "EQUIPMENT_MAINHAND_TWO_HANDED",
      CROSSBOW_ONE_HANDED: "EQUIPMENT_MAINHAND_CROSSBOW_ONE_HANDED",
      CROSSBOW_TWO_HANDED: "EQUIPMENT_MAINHAND_CROSSBOW_TWO_HANDED",
      THROWING: "EQUIPMENT_MAINHAND_THROWING"
    },
  },
  OFFHAND: {
    ONE_HANDED: {
      CROSSBOW: {
        UNDER:  "EQUIPMENT_OFFHAND_CROSSBOW_ONE_HANDED_UNDER",
        OVER: 'EQUIPMENT_OFFHAND_CROSSBOW_ONE_HANDED_OVER'
      },
      SHIELD: {
        UNDER: "EQUIPMENT_OFFHAND_SHIELD_UNDER"
      }
    }
  },
  MAINHAND: {
    ONE_HANDED: {
      DEFAULT: {
        UNDER: "EQUIPMENT_MAINHAND_ONE_HANDED_UNDER"
      },
      CROSSBOW: {
        UNDER: 'EQUIPMENT_MAINHAND_CROSSBOW_ONE_HANDED_UNDER',
        OVER: 'EQUIPMENT_MAINHAND_CROSSBOW_ONE_HANDED_OVER'
      }
    },
    TWO_HANDED: {
      CROSSBOW: {
        UNDER: 'EQUIPMENT_MAINHAND_CROSSBOW_TWO_HANDED_UNDER',
        OVER: 'EQUIPMENT_MAINHAND_CROSSBOW_TWO_HANDED_OVER'
      }
    }
  },
  GLOVES: {
    UNDER: "EQUIPMENT_GLOVES_UNDER",
    OVER: "EQUIPMENT_GLOVES_OVER"
  },
  PANTS: {
    UNTUCKED: "EQUIPMENT_PANTS_UNTUCKED",
    TUCKED: "EQUIPMENT_PANTS_TUCKED" // not implemented yet, I think we'll want to dynamically apply this based on chest
  },
  BOOTS: {
    TUCKED: "EQUIPMENT_BOOTS_TUCKED",
    UNTUCKED: "EQUIPMENT_BOOTS_UNTUCKED"
  },
} as const;
