import { EQUIPMENT } from "./equipmentLayer";
import { BODY } from "./baseLayer";

/** Layer stack order: higher number draws on top. Entries below are sorted high → low. */
export const zIndex = {
  [EQUIPMENT.OFFHAND.ONE_HANDED.SHIELD.UNDER]: 505,
  [EQUIPMENT.HELM]: 500,
  [BODY.HAIR.OVER]: 480,
  /** Body/base — not shared with equipment layer ids; when order matched equipment, value is equipment zIndex − 1. */
  [BODY.HEAD.BASE]: 475,
  [EQUIPMENT.CHEST.MAINHAND.TWO_HANDED]: 430,
  [BODY.OFFHAND.TWO_HANDED.UNDER]: 429,
  [BODY.MAINHAND.TWO_HANDED.OVER]: 410,
  [BODY.OFFHAND.TWO_HANDED.OVER]: 370,
  [EQUIPMENT.CHEST.OFFHAND.TWO_HANDED]: 350,
  [BODY.MAINHAND.TWO_HANDED.UNDER]: 349,
  [EQUIPMENT.MAINHAND.TWO_HANDED.UNDER]: 340,
  [EQUIPMENT.CHEST.MAINHAND.CROSSBOW_TWO_HANDED]: 330,
  [BODY.OFFHAND.TWO_HANDED_CROSSBOW.UNDER]: 329,
  [BODY.MAINHAND.TWO_HANDED_CROSSBOW.OVER]: 320,
  [EQUIPMENT.MAINHAND.TWO_HANDED.OVER]: 310,
  [EQUIPMENT.OFFHAND.ONE_HANDED.CROSSBOW.UNDER]: 290,
  [EQUIPMENT.CHEST.MAINHAND.CROSSBOW_ONE_HANDED]: 285,
  [BODY.OFFHAND.ONE_HANDED_CROSSBOW.UNDER]: 284,
  [EQUIPMENT.OFFHAND.ONE_HANDED.CROSSBOW.OVER]: 275,
  [EQUIPMENT.MAINHAND.ONE_HANDED.CROSSBOW.OVER]: 274,
  [EQUIPMENT.MAINHAND.ONE_HANDED.CROSSBOW.UNDER]: 270,
  [EQUIPMENT.CHEST.MAINHAND.ONE_HANDED]: 265,
  [BODY.OFFHAND.ONE_HANDED.UNDER]: 264,
  [BODY.MAINHAND.ONE_HANDED_THROWING.UNDER]: 264,
  [BODY.OFFHAND.ONE_HANDED.OVER]: 255,
  [EQUIPMENT.CHEST.OFFHAND.THROWING]: 230,
  [EQUIPMENT.CHEST.MAINHAND.THROWING]: 225,
  [BODY.OFFHAND.ONE_HANDED_THROWING.UNDER]: 224,
  [EQUIPMENT.CHEST.BODY.UNTUCKED]: 223,
  [EQUIPMENT.BOOTS.UNTUCKED]: 220,
  [EQUIPMENT.PANTS.UNTUCKED]: 210,
  [BODY.UNDERWEAR.BOTTOM]: 209,
  /** Under-layer for pants (e.g. leggings); between chest and `PANTSOVER`. */
  [EQUIPMENT.PANTS.TUCKED]: 205,
  [EQUIPMENT.CHEST.BODY.TUCKED]: 200,
  [BODY.BODY.BASE]: 199,
  [EQUIPMENT.BOOTS.TUCKED]: 170,
  [EQUIPMENT.CHEST.OFFHAND.CROSSBOW_TWO_HANDED]: 90,
  [BODY.MAINHAND.TWO_HANDED_CROSSBOW.UNDER]: 89,
  [BODY.MAINHAND.ONE_HANDED.OVER]: 70,
  [EQUIPMENT.MAINHAND.ONE_HANDED.DEFAULT.UNDER]: 60,
  [EQUIPMENT.CHEST.OFFHAND.ONE_HANDED]: 50,
  [BODY.MAINHAND.ONE_HANDED.UNDER]: 49,
  [EQUIPMENT.CHEST.OFFHAND.CROSSBOW_ONE_HANDED]: 30,
  [BODY.MAINHAND.ONE_HANDED_CROSSBOW.UNDER]: 29,
  //[EQUIPMENT.CHEST.CROSSBOW.ONE_HANDED.LEFT_BODY]: 20,
} as const;

/** Semantic layer id (matches keys of `zIndex`). Equipment image rows reference this; numbers resolve at build time. */
export type ZIndexLayerKey = keyof typeof zIndex;

export function zIndexValue(layer: ZIndexLayerKey): number {
  return zIndex[layer];
}
